[toolchain]

[features]
resolution = true
skip-lint = false

#change the pubkey with a hardcoded value or from other sources
[programs.localnet]
my_anchor_program = "pubkey"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
