[toolchain]

[features]
resolution = true
skip-lint = false

#change the pubkey with a hardcoded value or from other sources
[programs.localnet]
test = "pubkey"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
